#!/usr/bin/env python3
"""Static site generator for Tech2You.

Reads prompts/examples/*.yaml and topic_radar/digests/*.md and renders a
plain static site into docs/ — no build tooling, no JS framework, so it can
be previewed by opening docs/index.html directly, or served for free via
GitHub Pages (repo settings -> Pages -> serve from /docs on main).

Usage: python site/generate.py
"""

import html
import shutil
from pathlib import Path

import markdown as md
from ruamel.yaml import YAML

ROOT = Path(__file__).resolve().parent.parent
PROMPTS_DIR = ROOT / "prompts" / "examples"
DIGESTS_DIR = ROOT / "topic_radar" / "digests"
OUT_DIR = ROOT / "docs"

yaml = YAML()

NAV = [("index.html", "Home"), ("prompts.html", "Prompt Library"), ("digests.html", "Topic Radar")]

CSS = """
:root {
  --bg: #0b0d12;
  --bg-card: #131720;
  --border: #232838;
  --text: #e6e9f0;
  --text-dim: #8b93a7;
  --accent: #7dd3c0;
  --accent-2: #a78bfa;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
  line-height: 1.55;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1.1rem 1.5rem;
  border-bottom: 1px solid var(--border);
  position: sticky;
  top: 0;
  background: rgba(11,13,18,0.9);
  backdrop-filter: blur(6px);
}
header .brand {
  font-weight: 700;
  font-size: 1.15rem;
  color: var(--text);
  letter-spacing: -0.01em;
}
header .brand span { color: var(--accent); }
header nav a {
  color: var(--text-dim);
  margin-left: 1.25rem;
  font-size: 0.92rem;
}
header nav a.active, header nav a:hover { color: var(--text); text-decoration: none; }
main {
  max-width: 880px;
  margin: 0 auto;
  padding: 2.5rem 1.5rem 5rem;
}
.hero { padding: 2.5rem 0 3rem; }
.hero h1 { font-size: 2.1rem; margin: 0 0 0.6rem; letter-spacing: -0.02em; }
.hero p { color: var(--text-dim); font-size: 1.05rem; max-width: 640px; }
.pillars { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-top: 2rem; }
@media (max-width: 640px) { .pillars { grid-template-columns: 1fr; } }
.card {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1.25rem 1.4rem;
  margin-bottom: 1rem;
}
.card h3 { margin: 0 0 0.4rem; font-size: 1.05rem; }
.card p { color: var(--text-dim); margin: 0 0 0.6rem; font-size: 0.92rem; }
.badge {
  display: inline-block;
  font-size: 0.72rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--accent);
  background: rgba(125,211,192,0.1);
  border: 1px solid rgba(125,211,192,0.25);
  border-radius: 6px;
  padding: 0.15rem 0.5rem;
  margin-right: 0.4rem;
}
.badge.alt { color: var(--accent-2); background: rgba(167,139,250,0.1); border-color: rgba(167,139,250,0.25); }
.empty { color: var(--text-dim); font-size: 0.95rem; padding: 1.5rem 0; }
pre {
  background: #0e1118;
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 1rem;
  overflow-x: auto;
  font-size: 0.85rem;
  color: #d7dce6;
}
code { font-family: "SF Mono", Consolas, monospace; }
.meta { color: var(--text-dim); font-size: 0.85rem; margin-bottom: 1.4rem; }
.meta code { color: var(--text); }
h2 { font-size: 1.35rem; margin-top: 2.2rem; }
.back { display: inline-block; margin-bottom: 1.5rem; color: var(--text-dim); font-size: 0.9rem; }
footer { text-align: center; color: var(--text-dim); font-size: 0.82rem; padding: 2rem 0; }
"""


def layout(title: str, body: str, active: str) -> str:
    nav_html = "".join(
        f'<a href="{href}"{" class=active" if href == active else ""}>{label}</a>' for href, label in NAV
    )
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)} · Tech2You</title>
<style>{CSS}</style>
</head>
<body>
<header>
  <a class="brand" href="index.html">Tech2<span>You</span></a>
  <nav>{nav_html}</nav>
</header>
<main>
{body}
</main>
<footer>Tech2You — AI literacy hub. Generated by site/generate.py.</footer>
</body>
</html>"""


def load_prompts() -> list:
    prompts = []
    if PROMPTS_DIR.exists():
        for path in sorted(PROMPTS_DIR.glob("*.yaml")):
            with open(path, encoding="utf-8") as f:
                data = yaml.load(f)
            data["_slug"] = path.stem
            prompts.append(data)
    return prompts


def load_digests() -> list:
    digests = []
    if DIGESTS_DIR.exists():
        for path in sorted(DIGESTS_DIR.glob("*.md"), reverse=True):
            digests.append(path)
    return digests


def build_index(prompts: list, digests: list) -> str:
    body = f"""
<div class="hero">
  <h1>Tech2You</h1>
  <p>Personal AI-literacy hub — reusable prompt building blocks for agents and
  pipelines, plus a Claude/Gemini-curated radar of trending AI topics worth
  making a video about.</p>
</div>
<div class="pillars">
  <div class="card">
    <h3>Prompt Library</h3>
    <p>{len(prompts)} prompt/agent recipe{"s" if len(prompts) != 1 else ""} — composable, graph-aware,
    scored by an LLM eval harness.</p>
    <a href="prompts.html">Browse prompts &rarr;</a>
  </div>
  <div class="card">
    <h3>Topic Radar</h3>
    <p>{len(digests)} digest{"s" if len(digests) != 1 else ""} — trending AI topics pulled from free
    APIs, curated into video angles.</p>
    <a href="digests.html">Browse digests &rarr;</a>
  </div>
</div>
"""
    return layout("Home", body, "index.html")


def build_prompts_list(prompts: list) -> str:
    if not prompts:
        cards = '<div class="empty">No prompts yet — add one under <code>prompts/examples/</code>.</div>'
    else:
        cards = ""
        for p in prompts:
            eval_block = p.get("eval") or {}
            score = eval_block.get("score")
            badge = f'<span class="badge">{p.get("category", "")}</span>'
            if score is not None:
                badge += f'<span class="badge alt">score {score}/5</span>'
            cards += f"""<div class="card">
  <h3><a href="prompt-{p['_slug']}.html">{html.escape(p.get('title', p['_slug']))}</a></h3>
  <p>{html.escape(p.get('description', ''))}</p>
  {badge}
</div>
"""
    body = f"<h1>Prompt Library</h1>{cards}"
    return layout("Prompt Library", body, "prompts.html")


def build_prompt_detail(p: dict) -> str:
    graph = p.get("graph")
    graph_html = ""
    if graph:
        graph_html = f"""<h2>Graph position</h2>
<p class="meta">This prompt is a <code>{p.get('type')}</code> node: <code>{graph.get('position')}</code>
&mdash; upstream: <code>{', '.join(graph.get('upstream') or []) or 'none'}</code>,
downstream: <code>{', '.join(graph.get('downstream') or []) or 'none'}</code></p>"""

    variables = p.get("variables") or []
    var_rows = "".join(
        f"<li><code>{v.get('name')}</code> ({v.get('type')}{', required' if v.get('required') else ''}) — "
        f"{html.escape(v.get('description', ''))}</li>"
        for v in variables
    )

    eval_block = p.get("eval") or {}
    eval_html = ""
    if eval_block.get("last_run"):
        eval_html = f"""<h2>Latest eval</h2>
<p class="meta">Score: <code>{eval_block.get('score')}/5</code> &middot; Last run: <code>{eval_block.get('last_run')}</code></p>
<p class="meta">{html.escape(eval_block.get('notes') or '')}</p>"""

    body = f"""
<a class="back" href="prompts.html">&larr; All prompts</a>
<h1>{html.escape(p.get('title', p['_slug']))}</h1>
<p class="meta">
  <span class="badge">{p.get('category', '')}</span>
  <span class="badge alt">{(p.get('model') or {}).get('recommended', '')}</span>
</p>
<p>{html.escape(p.get('description', ''))}</p>
{graph_html}
<h2>Variables</h2>
<ul>{var_rows or '<li>none</li>'}</ul>
<h2>Prompt template</h2>
<pre><code>{html.escape(p.get('prompt', ''))}</code></pre>
{eval_html}
"""
    return layout(p.get("title", p["_slug"]), body, "prompts.html")


def build_digests_list(digests: list) -> str:
    if not digests:
        cards = (
            '<div class="empty">No digests yet — run '
            '<code>python topic_radar/digest.py</code> to generate one.</div>'
        )
    else:
        cards = ""
        for path in digests:
            cards += f"""<div class="card">
  <h3><a href="digest-{path.stem}.html">{path.stem}</a></h3>
</div>
"""
    body = f"<h1>Topic Radar</h1>{cards}"
    return layout("Topic Radar", body, "digests.html")


def build_digest_detail(path: Path) -> str:
    content = path.read_text(encoding="utf-8")
    rendered = md.markdown(content)
    body = f'<a class="back" href="digests.html">&larr; All digests</a>\n{rendered}'
    return layout(path.stem, body, "digests.html")


def main():
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)

    prompts = load_prompts()
    digests = load_digests()

    (OUT_DIR / "index.html").write_text(build_index(prompts, digests), encoding="utf-8")
    (OUT_DIR / "prompts.html").write_text(build_prompts_list(prompts), encoding="utf-8")
    (OUT_DIR / "digests.html").write_text(build_digests_list(digests), encoding="utf-8")

    for p in prompts:
        (OUT_DIR / f"prompt-{p['_slug']}.html").write_text(build_prompt_detail(p), encoding="utf-8")

    for path in digests:
        (OUT_DIR / f"digest-{path.stem}.html").write_text(build_digest_detail(path), encoding="utf-8")

    print(f"Built {3 + len(prompts) + len(digests)} pages into {OUT_DIR}")


if __name__ == "__main__":
    main()
